#1
Seller.create(name: "Fatima" ,image:"/images/sellers/1_seller.jpg", location: "Songea, Tanzania", story: "From a young age, Fatima had always been interested textiles. She had a keen eye for discerning colours and styles, and spent her adolescent years helping her mother make clothes for her younger siblings as well as other children in her hometown. Viral chillwave Intelligentsia, Tofu Helvetica Shoreditch cronut locavore iPhone messenger bag. PBR&B fanny pack gluten-free, sriracha skateboard gentrify keffiyeh. Tofu meh bicycle rights before they sold out Bushwick. Blue Bottle lomo mlkshk, squid gentrify letterpress kogi food truck Shoreditch crucifix next level beard. Squid pork belly Pinterest, normcore next level Blue Bottle typewriter 8-bit church-key put a bird on it keytar +1 craft beer. Blog kogi Tumblr Vice, narwhal seitan bitters master cleanse dreamcatcher. Hella XOXO lomo, meggings 3 wolf moon whatever slow-carb fashion axe photo booth cliche raw denim sriracha.

Distillery try-hard viral, put a bird on it single-origin coffee ugh selvage before they sold out mixtape four dollar toast artisan gluten-free butcher mlkshk. Mlkshk art party dreamcatcher plaid, selvage narwhal wolf trust fund gentrify tofu mumblecore four dollar toast banh mi biodiesel. Heirloom lumbersexual chia pork belly salvia. Bitters health goth fashion axe fingerstache yr, Pinterest selfies. Trust fund lo-fi Williamsburg normcore gluten-free, twee authentic semiotics Thundercats sriracha disrupt tofu jean shorts. Intelligentsia ugh lo-fi scenester biodiesel, drinking vinegar sustainable umami polaroid paleo tattooed. Seitan flannel literally, plaid pork belly selfies YOLO.

Kogi wayfarers sriracha bicycle rights banjo wolf. Literally kitsch Etsy, roof party dreamcatcher lo-fi try-hard meh Shoreditch Portland High Life small batch forage Godard. Put a bird on it Godard fanny pack Bushwick Tumblr, Pitchfork butcher lomo kitsch flannel jean shorts kale chips. Godard Etsy tousled, PBR artisan Helvetica hoodie umami mumblecore Wes Anderson Intelligentsia Blue Bottle bespoke whatever. Literally gentrify Pitchfork crucifix, forage wayfarers butcher. Brunch actually dreamcatcher before they sold out, leggings readymade flannel master cleanse YOLO narwhal scenester. Wayfarers kitsch readymade retro.

DIY wolf Godard, ugh narwhal before they sold out lo-fi Banksy meditation ethical Austin blog meh heirloom.", blurb: "My goal is to start a clothing company that can provide for my town.", specialty: "Textile" , video: "https://www.youtube.com/watch?v=NhQJrz-aDfI")
#2
Seller.create(name: "Joseph" , image:"/images/sellers/5_seller.jpg", location: "Songea, Tanzania", story: "Joseph's dexterity and training in the field of visual arts allow him to create various products that range from artwork to necklaces, to woven baskets and contemporary sculptures. Viral chillwave  lo-fi try-hard meh Shoreditch Portland High Life small batch forage Godard. Put a bird on it Godard fanny pack Bushwick Tumblr, Pitchfork butcher lomo kitsch flannel jean shorts kale chips. Godard Etsy tousled, PBR artisan Helvetica hoodie umami mumblecore Wes Anderson Intelligentsia Blue Bottle bespoke whatever. Literally gentrify Pitchfork crucifix, forage wayfarers butcher. Brunch actually dreamcatcher before they sold out, leggings readymade flannel master cleanse YOLO narwhal scenester. Wayfarers kitsch readymade retro.

hurch-key XOXO meditation gluten-free kitsch. Keytar meggings Echo Park gentrify. Williamsburg salvia keffiyeh, brunch fixie farm-to-table normcore ennui Bushwick craft beer squid Godard Kickstarter lumbersexual four loko. Jean shorts you probably haven't heard of them gluten-free, cardigan freegan selvage trust fund bicycle rights try-hard brunch cray keffiyeh letterpress. Brunch shabby chic sustainable, flannel Blue Bottle distillery Echo Park migas Schlitz Carles ugh asymmetrical crucifix kitsch sriracha. Pug whateverTofu Helvetica Shoreditch cronut locavore iPhone messenger bag. PBR&B fanny pack gluten-free, sriracha skateboard gentrify keffiyeh. Tofu meh bicycle rights before they sold out Bushwick. Blue Bottle lomo mlkshk, squid gentrify letterpress kogi food truck Shoreditch crucifix next level beard. Squid pork belly Pinterest, normcore next level Blue Bottle typewriter 8-bit church-key put a bird on it keytar +1 craft beer. Blog kogi Tumblr Vice, narwhal seitan bitters master cleanse dreamcatcher. Hella XOXO lomo, meggings 3 wolf moon whatever slow-carb fashion axe photo booth cliche raw denim sriracha.

Kogi wayfarers sriracha bicycle iPhone narwhal brunch, blog yr YOLO tilde roof party butcher literally freegan vegan squid retro. Selfies authentic beard 8-bit Bushwick, Portland Brooklyn Vice four dollar toast put a bird on it Etsy cray art party biodiesel freegan. Etsy Wes Anderson leggings gentrify, drinking vinegar plaid Truffaut fap. Direct trade fixie tofu, quinoa meh freegan stumptown Kickstarter American Apparel shabby chic farm-to-table. Skateboard ethical farm-to-table salvia messenger bag deep v.", blurb: "I am an aspiring artist.", specialty: "Arts/Crafts" , video: "https://www.youtube.com/watch?v=NhQJrz-aDfI")  
#3
Seller.create(name: "James" , image:"/images/sellers/3_seller.jpg",location: "Songea, Tanzania", story: "Tofu Helvetica Shoreditch cronut locavore iPhone messenger bag. PBR&B fanny pack gluten-free, sriracha skateboard gentrify keffiyeh. Tofu meh bicycle rights before they sold out Bushwick. Blue Bottle lomo mlkshk, squid gentrify letterpress kogi food truck Shoreditch crucifix next level beard. Squid pork belly Pinterest, normcore next level Blue Bottle typewriter 8-bit church-key put a bird on it keytar +1 craft beer. Blog kogi Tumblr Vice, narwhal seitan bitters master cleanse dreamcatcher. Hella XOXO lomo, meggings 3 wolf moon whatever slow-carb fashion axe photo booth cliche raw denim sriracha.

DIY wolf Godard, ugh narwhal before they sold out lo-fi Banksy meditation ethical Austin blog meh heirloom. Church-key XOXO meditation gluten-free kitsch. Keytar meggings Echo Park gentrify. Williamsburg salvia keffiyeh, brunch fixie farm-to-table normcore ennui Bushwick craft beer squid Godard Kickstarter lumbersexual four loko. Jean shorts you probably haven't heard of them gluten-free, cardigan freegan selvage trust fund bicycle rights try-hard brunch cray keffiyeh letterpress. Brunch shabby chic sustainable, flannel Blue Bottle distillery Echo Park migas Schlitz Carles ugh asymmetrical crucifix kitsch sriracha. Pug whatever Austin Truffaut cred, tote bag Intelligentsia hoodie McSweeney's banjo next level fixie bicycle rights.PBR try-hard actually sartorial, four loko direct trade retro Vice leggings. Viral chillwave Intelligentsia, literally craft beer authentic chia lomo. Polaroid iPhone narwhal brunch, blog yr YOLO tilde roof party butcher literally freegan vegan squid retro. Selfies authentic beard 8-bit Bushwick, Portland Brooklyn Vice four dollar toast put a bird on it Etsy cray art party biodiesel freegan. Etsy Wes Anderson leggings gentrify, drinking vinegar plaid Truffaut fap. Direct trade fixie tofu, quinoa meh freegan stumptown Kickstarter American Apparel shabby chic farm-to-table. Skateboard ethical farm-to-table salvia messenger bag deep v.

Paleo hashtag crucifix, freegan beard flannel cardigan Shoreditch mumblecore tattooed 90's fap direct trade synth Brooklyn. Godard American Apparel Schlitz Carles small batch keytar Odd Future, pop-up yr leggings hoodie cornhole. Cornhole taxidermy keytar, synth four dollar toast American Apparel disrupt chambray meggings. Banjo Carles Schlitz, Etsy heirloom Blue Bottle Thundercats kogi gluten-free. Single-origin coffee McSweeney's next level, occupy butcher disrupt street art retro keytar Pitchfork bicycle rights readymade. Cardigan Vice Echo Park art party, scenester aesthetic migas McSweeney's kale chips Helvetica synth butcher heirloom put a bird on it letterpress. Farm-to-table +1 occupy, chillwave Godard YOLO Vice blog swag salvia beard mixtape seitan pop-up readymade.", blurb: "I am developing skills to support my family.", specialty: "Textile" , video: "https://www.youtube.com/watch?v=NhQJrz-aDfI")
#4
Seller.create(name: "Frida" , image:"/images/sellers/4_seller.jpg", location: "Songea, Tanzania", story: "Tofu Helvetica Shoreditch cronut locavore iPhone messenger bag. PBR&B fanny pack gluten-free, sriracha skateboard gentrify keffiyeh. Tofu meh bicycle rights before they sold out Bushwick. Blue Bottle lomo mlkshk, squid gentrify letterpress kogi food truck Shoreditch crucifix next level beard. Squid pork belly Pinterest, normcore next level Blue Bottle typewriter 8-bit church-key put a bird on it keytar +1 craft beer. Blog kogi Tumblr Vice, narwhal seitan bitters master cleanse dreamcatcher. Hella XOXO lomo, meggings 3 wolf moon whatever slow-carb fashion axe photo booth cliche raw denim sriracha.

DIY wolf Godard, ugh narwhal before they sold out lo-fi Banksy meditation ethical Austin blog meh heirloom. Church-key XOXO meditation gluten-free kitsch. Keytar meggings Echo Park gentrify. Williamsburg salvia keffiyeh, brunch fixie farm-to-table normcore ennui Bushwick craft beer squid Godard Kickstarter lumbersexual four loko. Jean shorts you probably haven't heard of them gluten-free, cardigan freegan selvage trust fund bicycle rights try-hard brunch cray keffiyeh letterpress. Brunch shabby chic sustainable, flannel Blue Bottle distillery Echo Park migas Schlitz Carles ugh asymmetrical crucifix kitsch sriracha. Pug whatever Austin Truffaut cred, tote bag Intelligentsia hoodie McSweeney's banjo next level fixie bicycle rights.PBR try-hard actually sartorial, four loko direct trade retro Vice leggings. Viral chillwave Intelligentsia, literally craft beer authentic chia lomo. Polaroid iPhone narwhal brunch, blog yr YOLO tilde roof party butcher literally freegan vegan squid retro. Selfies authentic beard 8-bit Bushwick, Portland Brooklyn Vice four dollar toast put a bird on it Etsy cray art party biodiesel freegan. Etsy Wes Anderson leggings gentrify, drinking vinegar plaid Truffaut fap. Direct trade fixie tofu, quinoa meh freegan stumptown Kickstarter American Apparel shabby chic farm-to-table. Skateboard ethical farm-to-table salvia messenger bag deep v.

Paleo hashtag crucifix, freegan beard flannel cardigan Shoreditch mumblecore tattooed 90's fap direct trade synth Brooklyn. Godard American Apparel Schlitz Carles small batch keytar Odd Future, pop-up yr leggings hoodie cornhole. Cornhole taxidermy keytar, synth four dollar toast American Apparel disrupt chambray meggings. Banjo Carles Schlitz, Etsy heirloom Blue Bottle Thundercats kogi gluten-free. Single-origin coffee McSweeney's next level, occupy butcher disrupt street art retro keytar Pitchfork bicycle rights readymade. Cardigan Vice Echo Park art party, scenester aesthetic migas McSweeney's kale chips Helvetica synth butcher heirloom put a bird on it letterpress. Farm-to-table +1 occupy, chillwave Godard YOLO Vice blog swag salvia beard mixtape seitan pop-up readymade.", blurb: "I am developing skills to support my family.", specialty: "Textile" , video: "https://www.youtube.com/watch?v=NhQJrz-aDfI")
#5
Seller.create(name: "Editha" , image:"/images/sellers/6_seller.jpg", location: "Songea, Tanzania", story: "Tofu Helvetica Shoreditch cronut locavore iPhone messenger bag. PBR&B fanny pack gluten-free, sriracha skateboard gentrify keffiyeh. Tofu meh bicycle rights before they sold out Bushwick. Blue Bottle lomo mlkshk, squid gentrify letterpress kogi food truck Shoreditch crucifix next level beard. Squid pork belly Pinterest, normcore next level Blue Bottle typewriter 8-bit church-key put a bird on it keytar +1 craft beer. Blog kogi Tumblr Vice, narwhal seitan bitters master cleanse dreamcatcher. Hella XOXO lomo, meggings 3 wolf moon whatever slow-carb fashion axe photo booth cliche raw denim sriracha.

DIY wolf Godard, ugh narwhal before they sold out lo-fi Banksy meditation ethical Austin blog meh heirloom. Church-key XOXO meditation gluten-free kitsch. Keytar meggings Echo Park gentrify. Williamsburg salvia keffiyeh, brunch fixie farm-to-table normcore ennui Bushwick craft beer squid Godard Kickstarter lumbersexual four loko. Jean shorts you probably haven't heard of them gluten-free, cardigan freegan selvage trust fund bicycle rights try-hard brunch cray keffiyeh letterpress. Brunch shabby chic sustainable, flannel Blue Bottle distillery Echo Park migas Schlitz Carles ugh asymmetrical crucifix kitsch sriracha. Pug whatever Austin Truffaut cred, tote bag Intelligentsia hoodie McSweeney's banjo next level fixie bicycle rights.BR try-hard actually sartorial, four loko direct trade retro Vice leggings. Viral chillwave Intelligentsia, literally craft beer authentic chia lomo. Polaroid iPhone narwhal brunch, blog yr YOLO tilde roof party butcher literally freegan vegan squid retro. Selfies authentic beard 8-bit Bushwick, Portland Brooklyn Vice four dollar toast put a bird on it Etsy cray art party biodiesel freegan. Etsy Wes Anderson leggings gentrify, drinking vinegar plaid Truffaut fap. Direct trade fixie tofu, quinoa meh freegan stumptown Kickstarter American Apparel shabby chic farm-to-table. Skateboard ethical farm-to-table salvia messenger bag deep v.

Paleo hashtag crucifix, freegan beard flannel cardigan Shoreditch mumblecore tattooed 90's fap direct trade synth Brooklyn. Godard American Apparel Schlitz Carles small batch keytar Odd Future, pop-up yr leggings hoodie cornhole. Cornhole taxidermy keytar, synth four dollar toast American Apparel disrupt chambray meggings. Banjo Carles Schlitz, Etsy heirloom Blue Bottle Thundercats kogi gluten-free. Single-origin coffee McSweeney's next level, occupy butcher disrupt street art retro keytar Pitchfork bicycle rights readymade. Cardigan Vice Echo Park art party, scenester aesthetic migas McSweeney's kale chips Helvetica synth butcher heirloom put a bird on it letterpress. Farm-to-table +1 occupy, chillwave Godard YOLO Vice blog swag salvia beard mixtape seitan pop-up readymade.", blurb: "I am developing skills to support my family.", specialty: "Textile" , video: "https://www.youtube.com/watch?v=NhQJrz-aDfI")
#6
Seller.create(name: "Emmanuel", image:"/images/sellers/8_seller.jpg" , location: "Songea, Tanzania", story: "Tofu Helvetica Shoreditch cronut locavore iPhone messenger bag. PBR&B fanny pack gluten-free, sriracha skateboard gentrify keffiyeh. Tofu meh bicycle rights before they sold out Bushwick. Blue Bottle lomo mlkshk, squid gentrify letterpress kogi food truck Shoreditch crucifix next level beard. Squid pork belly Pinterest, normcore next level Blue Bottle typewriter 8-bit church-key put a bird on it keytar +1 craft beer. Blog kogi Tumblr Vice, narwhal seitan bitters master cleanse dreamcatcher. Hella XOXO lomo, meggings 3 wolf moon whatever slow-carb fashion axe photo booth cliche raw denim sriracha.

DIY wolf Godard, ugh narwhal before they sold out lo-fi Banksy meditation ethical Austin blog meh heirloom. Church-key XOXO meditation gluten-free kitsch. Keytar meggings Echo Park gentrify. Williamsburg salvia keffiyeh, brunch fixie farm-to-table normcore ennui Bushwick craft beer squid Godard Kickstarter lumbersexual four loko. Jean shorts you probably haven't heard of them gluten-free, cardigan freegan selvage trust fund bicycle rights try-hard brunch cray keffiyeh letterpress. Brunch shabby chic sustainable, flannel Blue Bottle distillery Echo Park migas Schlitz Carles ugh asymmetrical crucifix kitsch sriracha. Pug whatever Austin Truffaut cred, tote bag Intelligentsia hoodie McSweeney's banjo next level fixie bicycle rights.PBR try-hard actually sartorial, four loko direct trade retro Vice leggings. Viral chillwave Intelligentsia, literally craft beer authentic chia lomo. Polaroid iPhone narwhal brunch, blog yr YOLO tilde roof party butcher literally freegan vegan squid retro. Selfies authentic beard 8-bit Bushwick, Portland Brooklyn Vice four dollar toast put a bird on it Etsy cray art party biodiesel freegan. Etsy Wes Anderson leggings gentrify, drinking vinegar plaid Truffaut fap. Direct trade fixie tofu, quinoa meh freegan stumptown Kickstarter American Apparel shabby chic farm-to-table. Skateboard ethical farm-to-table salvia messenger bag deep v.

Paleo hashtag crucifix, freegan beard flannel cardigan Shoreditch mumblecore tattooed 90's fap direct trade synth Brooklyn. Godard American Apparel Schlitz Carles small batch keytar Odd Future, pop-up yr leggings hoodie cornhole. Cornhole taxidermy keytar, synth four dollar toast American Apparel disrupt chambray meggings. Banjo Carles Schlitz, Etsy heirloom Blue Bottle Thundercats kogi gluten-free. Single-origin coffee McSweeney's next level, occupy butcher disrupt street art retro keytar Pitchfork bicycle rights readymade. Cardigan Vice Echo Park art party, scenester aesthetic migas McSweeney's kale chips Helvetica synth butcher heirloom put a bird on it letterpress. Farm-to-table +1 occupy, chillwave Godard YOLO Vice blog swag salvia beard mixtape seitan pop-up readymade.", blurb: "I am developing skills to support my family.", specialty: "Textile" , video: "https://www.youtube.com/watch?v=NhQJrz-aDfI")
#7
Seller.create(name: "Ibrahim" , image:"/images/sellers/9_seller.jpg", location: "Songea, Tanzania", story: "Tofu Helvetica Shoreditch cronut locavore iPhone messenger bag. PBR&B fanny pack gluten-free, sriracha skateboard gentrify keffiyeh. Tofu meh bicycle rights before they sold out Bushwick. Blue Bottle lomo mlkshk, squid gentrify letterpress kogi food truck Shoreditch crucifix next level beard. Squid pork belly Pinterest, normcore next level Blue Bottle typewriter 8-bit church-key put a bird on it keytar +1 craft beer. Blog kogi Tumblr Vice, narwhal seitan bitters master cleanse dreamcatcher. Hella XOXO lomo, meggings 3 wolf moon whatever slow-carb fashion axe photo booth cliche raw denim sriracha.

DIY wolf Godard, ugh narwhal before they sold out lo-fi Banksy meditation ethical Austin blog meh heirloom. Church-key XOXO meditation gluten-free kitsch. Keytar meggings Echo Park gentrify. Williamsburg salvia keffiyeh, brunch fixie farm-to-table normcore ennui Bushwick craft beer squid Godard Kickstarter lumbersexual four loko. Jean shorts you probably haven't heard of them gluten-free, cardigan freegan selvage trust fund bicycle rights try-hard brunch cray keffiyeh letterpress. Brunch shabby chic sustainable, flannel Blue Bottle distillery Echo Park migas Schlitz Carles ugh asymmetrical crucifix kitsch sriracha. Pug whatever Austin Truffaut cred, tote bag Intelligentsia hoodie McSweeney's banjo next level fixie bicycle rights.PBR try-hard actually sartorial, four loko direct trade retro Vice leggings. Viral chillwave Intelligentsia, literally craft beer authentic chia lomo. Polaroid iPhone narwhal brunch, blog yr YOLO tilde roof party butcher literally freegan vegan squid retro. Selfies authentic beard 8-bit Bushwick, Portland Brooklyn Vice four dollar toast put a bird on it Etsy cray art party biodiesel freegan. Etsy Wes Anderson leggings gentrify, drinking vinegar plaid Truffaut fap. Direct trade fixie tofu, quinoa meh freegan stumptown Kickstarter American Apparel shabby chic farm-to-table. Skateboard ethical farm-to-table salvia messenger bag deep v.

Paleo hashtag crucifix, freegan beard flannel cardigan Shoreditch mumblecore tattooed 90's fap direct trade synth Brooklyn. Godard American Apparel Schlitz Carles small batch keytar Odd Future, pop-up yr leggings hoodie cornhole. Cornhole taxidermy keytar, synth four dollar toast American Apparel disrupt chambray meggings. Banjo Carles Schlitz, Etsy heirloom Blue Bottle Thundercats kogi gluten-free. Single-origin coffee McSweeney's next level, occupy butcher disrupt street art retro keytar Pitchfork bicycle rights readymade. Cardigan Vice Echo Park art party, scenester aesthetic migas McSweeney's kale chips Helvetica synth butcher heirloom put a bird on it letterpress. Farm-to-table +1 occupy, chillwave Godard YOLO Vice blog swag salvia beard mixtape seitan pop-up readymade.", blurb: "I am developing skills to support my family.", specialty: "Textile" , video: "https://www.youtube.com/watch?v=NhQJrz-aDfI")
#8
Seller.create(name: "Maria", image:"/images/sellers/2_seller.jpg" , location: "Songea, Tanzania", story: "Tofu Helvetica Shoreditch cronut locavore iPhone messenger bag. PBR&B fanny pack gluten-free, sriracha skateboard gentrify keffiyeh. Tofu meh bicycle rights before they sold out Bushwick. Blue Bottle lomo mlkshk, squid gentrify letterpress kogi food truck Shoreditch crucifix next level beard. Squid pork belly Pinterest, normcore next level Blue Bottle typewriter 8-bit church-key put a bird on it keytar +1 craft beer. Blog kogi Tumblr Vice, narwhal seitan bitters master cleanse dreamcatcher. Hella XOXO lomo, meggings 3 wolf moon whatever slow-carb fashion axe photo booth cliche raw denim sriracha.

Distillery try-hard viral, put a bird on it single-origin coffee ugh selvage before they sold out mixtape four dollar toast artisan gluten-free butcher mlkshk. Mlkshk art party dreamcatcher plaid, selvage narwhal wolf trust fund gentrify tofu mumblecore four dollar toast banh mi biodiesel. Heirloom lumbersexual chia pork belly salvia. Bitters health goth fashion axe fingerstache yr, Pinterest selfies. Trust fund lo-fi Williamsburg normcore gluten-free, twee authentic semiotics Thundercats sriracha disrupt tofu jean shorts. Intelligentsia ugh lo-fi scenester biodiesel, drinking vinegar sustainable umami polaroid paleo tattooed. Seitan flannel literally, plaid pork belly selfies YOLO.

Paleo hashtag crucifix, freegan beard flannel cardigan Shoreditch mumblecore tattooed 90's fap direct trade synth Brooklyn. Godard American Apparel Schlitz Carles small batch keytar Odd Future, pop-up yr leggings hoodie cornhole. Cornhole taxidermy keytar, synth four dollar toast American Apparel disrupt chambray meggings. Banjo Carles Schlitz, Etsy heirloom Blue Bottle Thundercats kogi gluten-free. Single-origin coffee McSweeney's next level, occupy butcher disrupt street art retro keytar Pitchfork bicycle rights readymade. Cardigan Vice Echo Park art party, scenester aesthetic migas McSweeney's kale chips Helvetica synth butcher heirloom put a bird on it letterpress. Farm-to-table +1 occupy, chillwave Godard YOLO Vice blog swag salvia beard mixtape seitan pop-up readymade.", blurb: "I am developing skills to support my family.", specialty: "Textile" , video: "https://www.youtube.com/watch?v=NhQJrz-aDfI")
#9
Seller.create(name: "Peter" , image:"/images/sellers/7_seller.jpg",location: "Songea, Tanzania", story: "Tofu Helvetica Shoreditch cronut locavore iPhone messenger bag. PBR&B fanny pack gluten-free, sriracha skateboard gentrify keffiyeh. Tofu meh bicycle rights before they sold out Bushwick. Blue Bottle lomo mlkshk, squid gentrify letterpress kogi food truck Shoreditch crucifix next level beard. Squid pork belly Pinterest, normcore next level Blue Bottle typewriter 8-bit church-key put a bird on it keytar +1 craft beer. Blog kogi Tumblr Vice, narwhal seitan bitters master cleanse dreamcatcher. Hella XOXO lomo, meggings 3 wolf moon whatever slow-carb fashion axe photo booth cliche raw denim sriracha.

Kogi wayfarers sriracha bicycle rights banjo wolf. Literally kitsch Etsy, roof party dreamcatcher lo-fi try-hard meh Shoreditch Portland High Life small batch forage Godard. Put a bird on it Godard fanny pack Bushwick Tumblr, Pitchfork butcher lomo kitsch flannel jean shorts kale chips. Godard Etsy tousled, PBR artisan Helvetica hoodie umami mumblecore Wes Anderson Intelligentsia Blue Bottle bespoke whatever. Literally gentrify Pitchfork crucifix, forage wayfarers butcher. Brunch actually dreamcatcher before they sold out, leggings readymade flannel master cleanse YOLO narwhal scenester. Wayfarers kitsch readymade retro.

Paleo hashtag crucifix, freegan beard flannel cardigan Shoreditch mumblecore tattooed 90's fap direct trade synth Brooklyn. Godard American Apparel Schlitz Carles small batch keytar Odd Future, pop-up yr leggings hoodie cornhole. Cornhole taxidermy keytar, synth four dollar toast American Apparel disrupt chambray meggings. Banjo Carles Schlitz, Etsy heirloom Blue Bottle Thundercats kogi gluten-free. Single-origin coffee McSweeney's next level, occupy butcher disrupt street art retro keytar Pitchfork bicycle rights readymade. Cardigan Vice Echo Park art party, scenester aesthetic migas McSweeney's kale chips Helvetica synth butcher heirloom put a bird on it letterpress. Farm-to-table +1 occupy, chillwave Godard YOLO Vice blog swag salvia beard mixtape seitan pop-up readymade.", blurb: "I am developing skills to support my family.", specialty: "Textile" , video: "https://www.youtube.com/watch?v=NhQJrz-aDfI")






# 1
Product.create(name: "Shopping Tote" , description: "This is a greate tote offering a modern handbag silhouette that reflects a woman's confident personal style. Work-appropriate, clean and sophisticated, AK Anne Klein handbags are made for the woman who wants timeless style. The brand offers function and fashion that is instantly wearable and always comfortable.", category: "Clothing and Accessories", price: 15, seller_id: 1)
#2
Product.create(name: "AFRICAN maxi" , description: "The AFRICAN WOMAN maxi skirt is a classic maxi skirt and sits comfortably at the waist. This skirt boasts beautiful colors, perfect for the warmer days ahead.", category: "Clothing and Accessories", price: 45, seller_id: 1)
#3
Product.create(name: "Baba Tree Baskets" , description: "We have a large selection of African baskets from Bolgatanga in various sizes and patterns. To purchase a basket and see our available stock for online sales please visit the online sales page. You will pay securlely with VISA, MC, your bank account or your PayPal account. We use PayPal to facilitate all your online shopping needs.", category: "Woven Products", price: 50, seller_id: 1)
#4
Product.create(name: "Weave Basket" , description: "This is a one of a kind woven basket, made from local plants, we have created a stylish product for a modern woman.", category: "Clothing and Accessories", price: 35, seller_id: 1)
#5
Product.create(name: "The Elephant" , description: "African Elephants are endangered and we believe that wherever possible they should be allowed to exist naturally in their native habitats. Unfortunately however, there are many elephants remaining in captivity with little protection and no habitat left to return to. Through this project we aim to educate the public about the elephants’ plight, educate caretakers in humane care practices, and raise funds to provide support and care to both captive and wild populations. 

  These elephant paintings are all original works of art and are available for purchase. Please help to support this important cause. Get your elephant painting online today!", category: "Paintings/ Batik", price: 100, seller_id: 1)
#6
Product.create(name: "VW Wire Car" , description: "Made by the boys highschool in kibera, these wire carts are used as toys. We have a varying set of cars and types. If you would like a custom design please feel free to contact us.", category: "Other", price: 20, seller_id: 1)
#7
Product.create(name: "Boko Fishing Basket" , description: "We have a large selection of African baskets from Bolgatanga in various sizes and patterns. To purchase a basket and see our available stock for online sales please visit the online sales page.", category: "Woven Products", price: 50, seller_id: 1)
#8
Product.create(name: "Massai Keychain" , description: "Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig ", category: "Other", price: 15, seller_id: 1)
#9
Product.create(name: "Boso Large Wall Weave" , description: "Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig ", category: "Other", price: 105, seller_id: 1)
#10
Product.create(name: "Savanah Animals" , description: "Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig", category: "Woven Products", price: 200, seller_id: 1)
#11
Product.create(name: "Massai Sculpture" , description: "This would work as a great decorational piece, we have lots of items simillar to this. Each sculpture is unique", category: "Sculpture", price: 50, seller_id: 1)
#12
Product.create(name: "Wire Art Radio" , description: "Created from recycled products, this art piece would make a great addition to any isplay case.", category: "Clothing and Accessories", price: 35, seller_id: 1)
#13
Product.create(name: "Massai Boy" , description: "Painted during the evening of the night eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig.", category: "Paintings/ Batik", price: 31, seller_id: 2)
#14
Product.create(name: "Day at the Watering Hole" , description: "Painted during the evening of the night eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig.", category: "Paintings/ Batik", price: 45, seller_id: 2)
#15
Product.create(name: "Village and Town" , description: "Painted during the evening of the night eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig.", category: "Paintings/ Batik", price: 65, seller_id: 2)
#16
Product.create(name: "The Rhino" , description: "Sculpted from scratch ma ma mia. Aute in reprehenderit, dolore aliqua non est magna in labore pig.", category: "Sculpture", price: 200, seller_id: 2)
#17
Product.create(name: "The Dancers" , description: "Sculpted from scratch ma ma mia. The artistic style is comprehensive you know.
  Aute in reprehenderit, dolore aliqua non est magna in labore pig.", category: "Sculpture", price: 150, seller_id: 2)
#18
Product.create(name: "Tears" , description: "Painted by the way from oil and canvas makes this unique. The artistic style is comprehensive you know.
  Aute in reprehenderit, dolore aliqua non est magna in labore pig.", category: "Sculpture", price: 245, seller_id: 2)
#19
Product.create(name: "In the desert" , description: "A tye and die explosion. The artistic style is comprehensive you know. Super duper, cool cool.
  Aute in reprehenderit, dolore aliqua non est magna in labore pig.", category: "Paintings/ Batik", price: 45, seller_id: 2)
#20
Product.create(name: "African Beauty" , description:"Sculpted from scratch ma ma mia. The artistic style is comprehensive you know.
  Aute in reprehenderit, dolore aliqua non est magna in labore pig.", category: "Paintings/ Batik", price: 350, seller_id: 2)
#21
Product.create(name: "Laundry Basket" , description: "A tye and die explosion. The artistic style is comprehensive you know. Super duper, cool cool.
  Aute in reprehenderit, dolore aliqua non est magna in labore pig.", category: "Woven Products", price: 65, seller_id: 2)


Image.create(file_path: "/images/products/1_product.jpg", product_id: 1)
Image.create(file_path: "/images/products/2_product.jpg", product_id: 2)
Image.create(file_path: "/images/products/3_product.jpg", product_id: 3)
Image.create(file_path: "/images/products/4_product.jpg", product_id: 4)
Image.create(file_path: "/images/products/5_product.jpg", product_id: 5)
Image.create(file_path: "/images/products/6_product.jpg", product_id: 6)
Image.create(file_path: "/images/products/7_product.jpg", product_id: 7)
Image.create(file_path: "/images/products/8_product.jpg", product_id: 8)
Image.create(file_path: "/images/products/9_product.jpg", product_id: 9)
Image.create(file_path: "/images/products/10_product.jpg", product_id: 10)
Image.create(file_path: "/images/products/11_product.jpg", product_id: 11)
Image.create(file_path: "/images/products/12_product.jpg", product_id: 12)
Image.create(file_path: "/images/products/13_product.jpeg", product_id: 13)
Image.create(file_path: "/images/products/14_product.jpg", product_id: 14)
Image.create(file_path: "/images/products/15_product.jpg", product_id: 15)
Image.create(file_path: "/images/products/16_product.jpg", product_id: 16)
Image.create(file_path: "/images/products/17_product.jpg", product_id: 17)
Image.create(file_path: "/images/products/18_product.jpg", product_id: 18)
Image.create(file_path: "/images/products/19_product.jpg", product_id: 19)
Image.create(file_path: "/images/products/20_product.jpg", product_id: 20)
Image.create(file_path: "/images/products/21_product.jpg", product_id: 21)

Buyer.create(name:"Bob")



